sudo: false # use new container
language: c

branches:
  except: /^(gh-pages|v[0-9]\..*)/

compiler:
  - clang
  - gcc
  - g++

addons:
  apt:
    packages:
      # xrdp
      - libpam0g-dev
      - libjpeg-dev
      - libfuse-dev
      - libmp3lame-dev
      - libx11-dev
      - libxrandr-dev
      - libpixman-1-dev
      - nasm
      # x11rdp
      #- flex
      #- bison
      #- libxml2-dev
      #- intltool
      #- xsltproc
      #- xutils-dev
      #- python-libxml2
      #- g++
      #- xutils

env:
  - CONF_FLAGS=""
  - CONF_FLAGS="--enable-ipv6 --enable-jpeg --enable-fuse --enable-mp3lame
                --enable-pixman --enable-rfxcodec --enable-painter"

script:
  - ./bootstrap
  - ./configure $CONF_FLAGS
  - make CFLAGS="-O2 -Wall -Wwrite-strings -Werror"
  - make distcheck
